### ISSUE TITLE
Get wrong result for lunar2solar

### ISSUE THREAD

**Issue by ghost** [StuPig/calendar-converter#1]
It seems the lib doesn't work for:

cc.lunar2solar(new Date(2013, 3, 13));
calElement {sYear: 2013, sMonth: 5, sDay: 22, week: "三", lYear: 2013…}

The correct result should be:

  lunar: 2013, 3, 13 -> solar: 2013, 4, 22
  lunar: 2013, 4, 13 -> solar: 2013, 5, 22

Please help to confirm and fix.

**Comment by StuPig** [comment]
@zhigang Firstly, I' m sorry that I didn't check this repository for such a long time. Your problem was not the lib's bug. You should know JavaScript's Date Object is very like Java's. When you type:

``` javascript
new Date(2013, 3, 13); // Sat Apr 13 2013 00:00:00 GMT+0800 (CST)
```

this just means 2013, 4, 13

**Comment by ghost** [comment]
Thanks for the tip. I don't know this: that was my first JavaScript app. Now fixed in my app.
