### ISSUE TITLE
好像除夕的代码应该是1230才对？

### ISSUE THREAD

**Issue by ipoly** [StuPig/calendar-converter#5]
现在是0100。

**Comment by StuPig** [comment]
@ipoly  设置为0100，是考虑不一定每年都有三十，现在已经修复。[https://github.com/StuPig/calendar-converter/commit/2114cfa1608a23eed147e24c030142a025cb27ac](https://github.com/StuPig/calendar-converter/commit/2114cfa1608a23eed147e24c030142a025cb27ac)

**Comment by ipoly** [comment]
试了一下，这样除夕当天显示的是春节。(tmp2 == '00'  &&  lunarMonth == 12 && lMonLen == lunarDay)这样才行。或者把除夕移动到列表第一条去。
